#!/bin/bash

## Value predefinition
requirements=("ssh" "sshpass" "curl")
app_conf_file=/usr/local/conf/check-disk-usage.ini



########################################
##          BASIC INFO SECTION        ##
########################################

   ##            FILENAME           ##
   ##       check-disk-storage      ##

   ##        DEFAULT_BIN_PATH       ##
   ##         /usr/local/bin        ##

   ##         REQUIRE_SUDO          ##
   ##           partially           ##

   ##          SCRIPT_BRIEF         ##
   ##   Sends a message if target   ##
   ##   server disk usage is over   ##
   ##              80%              ##

########################################


###################################
##     MAIN FUNCTION SECTION     ##
###################################

prepareEnviroment() {
    missing_apps=()
    for command in "${requirements[@]}" ; do
        if ! command -v "$command">/dev/null 2>&1 ; then
            missing_apps+=("$command")
        fi
    done

    if [ ! -z "${missing_apps[*]}" ]; then 
        if [[ $(id -u) -ne 0 ]]; then 
            echo "Error: Aplication(s)${missing_apps[*]} not found: You need may to run as root to install them"
            exit
        fi

        apt install "${missing_apps[@]}" -y
    fi

    log_dir="/var/log/check-disk-usage/"

    if [ ! -d "$log_dir" ] ; then 
        if [[ $(id -u) -ne 0 ]]; then 
            echo "Error: Directory $log_dir not found: You may need to run as root to create it"
            exit
        fi
        mkdir "$log_dir"
    fi


    app_conf_dir="/usr/local/conf/"

    if [ ! -d "$app_conf_dir" ] ; then 
        if [[ $(id -u) -ne 0 ]]; then 
            echo "Error: Directory $app_conf_dir not found: You may need to run as root to create it"
            exit
        fi
        mkdir "$app_conf_dir"
    fi
}

doInstall() {
    if [ "$1" != "reinstall" ] ; then
        if [[ ! -z $(which check-disk-usage) ]] ; then
            echo "Script already installed!"
            exit
        fi
    fi

    if [[ $(id -u) -ne 0 ]]; then 
        echo "Please, run as root if you want to $1"
        exit
    fi

    path_dir="/usr/local/bin/"
    script_file="$path_dir/check-disk-usage"
    touch "$script_file"
    IFS=$'\n' read -d '' -r -a lines < "$0"
    portable_script=( "${lines[@]::52}" "${lines[@]:82:14}" "${lines[@]:100}")
    installed_script=$(printf "%s\n" "${portable_script[@]}")
    echo "$installed_script" > "$script_file"
    chmod 777 "$script_file"
    
    if ! echo "$PATH" | grep -q -E -o '"[:]|/usr/local/bin|[:]"' ;  then
        path_config=$'# Make check-disk-usage script easier to execute\n'
        path_config+=$'if ! echo "$PATH" | grep -q -E -o "[:]|/usr/local/bin|[:]"\n'
        path_config+=$'    then\n'
        path_config+=$'    PATH="$PATH:/usr/local/bin"\n'
        path_config+=$'fi\n'

        echo "$path_config" >> /etc/environment
    fi
    exit
}

readArguments() {
    for arg in "$@" ; do
        if echo "$arg" | grep -q "\-p=" ; then
            use_ssh=true
            ssh_port=${arg:3}

        elif echo "$arg" | grep -q "\-t=" ; then
            use_ssh=true
            target="${arg:3}"

        elif echo "$arg" | grep -q "\-P=" ; then
            use_ssh=true;
            password="${arg:3}"

        elif echo "$arg" | grep -q "\-u=" ; then
            use_ssh=true
            user="${arg:3}"

        elif echo "$arg" | grep -q  "\--install" ; then
            doInstall install

        elif echo "$arg" | grep -q  "\--reinstall" ; then
            doInstall reinstall
        
        elif echo "$arg" | grep -q "\-l=" ; then
            language="${arg:3}"

        else
            echo -e "Unknown argument: $arg\nskipping..."
        fi
    done

    return 0;
}

rmFirst() {
    awk '{for (i=2; i<NF; i++) printf $i " "; print $NF}' <<< "$1"
}

readTargetConf() {
    readarray -t config < "$1"
    config+=( 'EOF' )

    for line in "${config[@]}" ; do
        if grep -Eq "\[*\]" <<< "$line" ; then
            T=$(sed -E -e 's/\[|\]//g' <<< "$line")
            target_switch=$((1))

        elif echo "$line"  | grep -q "port" ; then
            p=$(rmFirst "$line")
        elif echo "$line"  | grep -q "target" ; then
            t=$(rmFirst "$line")
        elif echo "$line"  | grep -q "user" ; then
            u=$(rmFirst "$line")
        elif echo "$line"  | grep -q "pass" ; then
            P=$(rmFirst "$line")
        elif [ "$line" = 'EOF' ] ; then
            target_switch=$((1))

        elif [ ! "$line" = "" ] ; then
            echo "Error: Invalid conf argument: $line"
        fi
        if [ "$t" = "localhost"  ] ; then
            p=0
            t="localhost"
            u="none"
            P="0"
            count=5
        fi

        if (( target_switch )) ; then
            tags+=( "$T" )
            ports+=( "$p" ) 
            targets+=( "$t" )
            users+=( "$u" ) 
            passwords+=( "$P" )
            target_switch=$((0))
        fi
    done
}

manageDefaultConf() {
    readarray -t config < "$1"

    for line in "${config[@]}" ; do
        if echo "$line"  | grep -q "ssh_port" && [ -z "$ssh_port" ] ; then
            ssh_port=$(rmFirst "$line")

        elif echo "$line"  | grep -q "use_conf" ; then
            use_conf=$(rmFirst "$line")

        elif echo "$line"  | grep -q "lang" ; then
            language=$(rmFirst "$line")

        elif echo "$line"  | grep -q "target_file" ; then
            target_file=$(rmFirst "$line")

        elif [ ! "$line" = "" ] ; then
            echo "Error: Invalid conf argument: $line"

        fi
    done
}

readAppConf() {
    readarray -t config < "$1"

    for line in "${config[@]}" ; do
        if echo "$line"  | grep -q "email" ; then
            zulip_email=$(rmFirst "$line")
        elif echo "$line"  | grep -q "key" ; then
            zulip_key=$(rmFirst "$line")
        elif echo "$line"  | grep -q "url" ; then
            zulip_url=$(rmFirst "$line")
        elif echo "$line"  | grep -q "stream" ; then
            zulip_stream=$(rmFirst "$line")
        elif echo "$line"  | grep -q "topic" ; then
            zulip_topic=$(rmFirst "$line")

        elif ! grep -Eq "\[*\]" <<< "$line" ; then
            echo "Error: Invalid conf argument: $line"
        fi
    done
}

parseMD() {
    readarray -t md_file < "$1"
    for i in "${md_file[@]}"; do
        document+="$i"$'\n'
    done

    echo "$document"
}

useLangSet() {
    if [ "$language" = "en" ] ; then
        message=$(parseMD /var/lang/en/check-disk-usage/heading.md) 
    elif [ "$language" = "es" ] ; then
        message=$(parseMD /var/lang/es/check-disk-usage/heading.md)
    elif [ "$language" = "cat" ] ; then
        message=$(parseMD /var/lang/cat/check-disk-usage/heading.md)
    fi
}

doCheck() {
    if [ "$use_conf" = "false" ] ; then
        if $use_ssh ; then
            if [ -z "$target" ] ; then
                echo -e "Warning: Target arg emtpy, using default target..."
                target="localhost"
            fi
            if [ -z "$password" ] ; then
                echo -e "Error: Password cannot be empty!"
                exit
            fi
            if [ -z "$user" ] ; then
                echo -e "Error: User cannot be empty!"
                exit
            fi
            if [ -z "$ssh_port" ] ; then
                echo -e "Warning: SSH port arg empty, using default port..."
                ssh_port=22
            fi

            output="$(sshpass -p "$password" ssh -o StrictHostKeyChecking=no -l "$user" "$target" -p "$ssh_port" "df -h /")"

        else
            output="$(df -h /)"    
        fi

        usage_percent=$( echo "${output}" | grep -E -o "[[:digit:]]{1,3}%" )
        usage_percent=${usage_percent:: -1}

        if (( usage_percent >= 80 )) ; then
            over_usage=true
            exit
        fi
        message+=$'\n- **'"$target"':** `'"$usage_percent"'%`'
    else
        readTargetConf "$target_file"
        count=$((1))

         unset 'tags[-1]'

        for tag in "${tags[@]}" ; do
            if [ "${targets[$count]}" = "localhost" ] ; then
                output="$(df -h /)"

            else
                if [ $((ports[count])) = 0 ] ; then
                    ssh_port=22
                else
                    ssh_port="${ports[$count]}"
                fi

                password="${passwords[$count]}"
                user="${users[$count]}"
                target="${targets[$count]}"

                output="$(sshpass -p "$password" ssh -o StrictHostKeyChecking=no -l "$user" "$target" -p "$ssh_port" "df -h /")"
            fi
            usage_percent=$( echo "${output}" | grep -E -o "[[:digit:]]{1,3}%" | sed 's/%$//')


            if (( usage_percent >= 80 )) ; then
                    message+=$'\n- **'"$tag"':** `'"$usage_percent"'%`'
                    over_usage="true"
            fi
            count=$(( count + 1 ))
        done
    fi
    echo "$message"
}

sendMessage() { 
    if $over_usage ; then
        curl -s -u "$zulip_email:$zulip_key" \
        -d "type=stream" \
        -d "to=$zulip_stream" \
        -d "topic=$zulip_topic" \
        --data-binary 'content='"$message"'' \
        "$zulip_url/api/v1/messages"
    fi
}

doLogging() {
    echo "CHECK %Y-%m-%d " >> "/var/log/check-disk-usage/$1.log";
}

prepareEnviroment
readArguments "$@"
manageDefaultConf "/etc/default/check-disk-usage.conf"
readAppConf "$app_conf_file"
useLangSet
doCheck
sendMessage

## Uncomment when it is ready ##
## doLogging